// Generated by Damned Memory Traversal Tool
// Base: 0x7ff70ed67140 Offsets: [[[base]+0x0]+0x40]+0x20]+0x0
// Base offset from module: 0x7140

#pragma once
#include <cstdint>
#include <vector>
#include <Windows.h>

constexpr uintptr_t BASE_OFFSET = 0x7140;

// Struct layout (use with direct memory access)
struct GameStruct {
    int32_t health; // 0x0
    int32_t max_health; // 0x4
    int32_t mp; // 0x8
    int32_t max_mp; // 0xC
};

// Pointer chain helper (use with ReadProcessMemory/WriteProcessMemory)
class GameStructReader {
    HANDLE hProcess;
    uintptr_t moduleBase;
    
    template<typename T>
    T Read(uintptr_t addr) {
        T val{};
        ReadProcessMemory(hProcess, (LPCVOID)addr, &val, sizeof(T), nullptr);
        return val;
    }
    
    template<typename T>
    bool Write(uintptr_t addr, T val) {
        return WriteProcessMemory(hProcess, (LPVOID)addr, &val, sizeof(T), nullptr);
    }
    
    // FollowChain: add offset, then read pointer (except for last offset)
    uintptr_t FollowChain(uintptr_t base, std::vector<int64_t> offsets) {
        uintptr_t addr = base;
        for (size_t i = 0; i < offsets.size(); i++) {
            addr = addr + offsets[i];
            if (i < offsets.size() - 1) {
                addr = Read<uintptr_t>(addr);
                if (addr == 0) return 0;
            }
        }
        return addr;
    }
    
public:
    GameStructReader(HANDLE process, uintptr_t base) : hProcess(process), moduleBase(base) {}
    
    int32_t getHealth() {
        return Read<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0x0}));
    }
    bool setHealth(int32_t val) {
        return Write<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0x0}), val);
    }
    
    int32_t getMax_health() {
        return Read<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0x4}));
    }
    bool setMax_health(int32_t val) {
        return Write<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0x4}), val);
    }
    
    int32_t getMp() {
        return Read<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0x8}));
    }
    bool setMp(int32_t val) {
        return Write<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0x8}), val);
    }
    
    int32_t getMax_mp() {
        return Read<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0xC}));
    }
    bool setMax_mp(int32_t val) {
        return Write<int32_t>(FollowChain(moduleBase + BASE_OFFSET, {0x0, 0x40, 0x20, 0xC}), val);
    }
    
};
